/* Generated by cbindgen */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * C-compatible validation configuration
 */
typedef struct CValidationConfig {
  /**
   * Maximum title length in characters
   */
  size_t max_title_length;
  /**
   * Maximum description length in characters
   */
  size_t max_description_length;
  /**
   * Allow dates in the future
   */
  bool allow_future_dates;
  /**
   * Minimum allowed year (e.g., 2000)
   */
  int32_t min_year;
  /**
   * Enable HTML sanitization
   */
  bool html_sanitize;
} CValidationConfig;

/**
 * Free a string returned by validate_news_article
 *
 * # Safety
 * The string must have been allocated by validate_news_article
 */
void free_c_string(char *s);

/**
 * Validate a news article
 *
 * # Parameters
 * - title: Article title (null-terminated UTF-8)
 * - link: Article URL (null-terminated UTF-8)
 * - description: Article description (null-terminated UTF-8, may contain HTML)
 * - published: Publication date (null-terminated UTF-8)
 * - source: News source name (null-terminated UTF-8)
 * - config: Validation configuration (NULL for defaults)
 *
 * # Returns
 * JSON string with validation results. Must be freed with free_c_string.
 *
 * # Safety
 * All input strings must be valid null-terminated UTF-8 strings.
 * The returned string must be freed with free_c_string.
 */
char *validate_news_article(const char *title,
                            const char *link,
                            const char *description,
                            const char *published,
                            const char *source,
                            const CValidationConfig *config);